In [1]:
#Importing the basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#importing the dataset
dataset = pd.read_csv("Covid Dataset.csv")

In [3]:
#displaying the head of the dataset
dataset.head()

Breathing Problem  Fever  Dry Cough  Sore throat  Running 0se  Asthma  \
0                  1      1          1            1            1       0   
1                  1      1          1            1            0       1   
2                  1      1          1            1            1       1   
3                  1      1          1            0            0       1   
4                  1      1          1            1            1       0   

   Chronic Lung Disease  Headache  Heart Disease  Diabetes  ...  Fatigue   \
0                     0         0              0         1  ...         1   
1                     1         1              0         0  ...         1   
2                     1         1              0         1  ...         1   
3                     0         0              1         1  ...         0   
4                     1         1              1         1  ...         0   

   Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0                  1              0                           1   
1                  0              0                           0   
2                  1              1                           0   
3                  0              1                           0   
4                  1              0                           1   

   Attended Large Gathering  Visited Public Exposed Places  \
0                         0                              1   
1                         1                              1   
2                         0                              0   
3                         1                              1   
4                         0                              1   

   Family working in Public Exposed Places  Wearing Masks  \
0                                        1              0   
1                                        0              0   
2                                        0              0   
3                                        0              0   
4                                        0              0   

   Sanitization from Market  COVID-19  
0                         0         1  
1                         0         1  
2                         0         1  
3                         0         1  
4                         0         1  

[5 rows x 21 columns]

In [4]:
#dividing the features and label
X = dataset.iloc[:,0:20]
Y = dataset.iloc[:,20]

In [5]:
X.head()

Breathing Problem  Fever  Dry Cough  Sore throat  Running 0se  Asthma  \
0                  1      1          1            1            1       0   
1                  1      1          1            1            0       1   
2                  1      1          1            1            1       1   
3                  1      1          1            0            0       1   
4                  1      1          1            1            1       0   

   Chronic Lung Disease  Headache  Heart Disease  Diabetes  Hyper Tension  \
0                     0         0              0         1              1   
1                     1         1              0         0              0   
2                     1         1              0         1              0   
3                     0         0              1         1              0   
4                     1         1              1         1              1   

   Fatigue   Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0         1                  1              0                           1   
1         1                  0              0                           0   
2         1                  1              1                           0   
3         0                  0              1                           0   
4         0                  1              0                           1   

   Attended Large Gathering  Visited Public Exposed Places  \
0                         0                              1   
1                         1                              1   
2                         0                              0   
3                         1                              1   
4                         0                              1   

   Family working in Public Exposed Places  Wearing Masks  \
0                                        1              0   
1                                        0              0   
2                                        0              0   
3                                        0              0   
4                                        0              0   

   Sanitization from Market  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0

In [6]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: COVID-19, dtype: int64

In [7]:
#defining Training , Testing Variables . Testing will be done on the 20% of the dataset and Training will be done on 80% of the dataset
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=.2,random_state=0)

In [8]:
#Transforming the points in smaller numerical value from the larger numerical value
from sklearn.preprocessing import StandardScaler

stc = StandardScaler()
X_train = stc.fit_transform(X_train)
X_test = stc.transform(X_test)

In [9]:
X_train

array([[-1.39826055,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       [ 0.71517429, -1.9076882 ,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       ...,
       [ 0.71517429,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [-1.39826055,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [ 0.71517429, -1.9076882 ,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ]])

In [10]:
X_test

array([[ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       [ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       [-1.39826055,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       ...,
       [ 0.71517429,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [-1.39826055, -1.9076882 , -1.93002591, ...,  1.19406082,
         0.        ,  0.        ],
       [ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ]])

In [11]:
X.shape

(5434, 20)

In [12]:
#Importing the Required Libraries for ANN
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import ReLU
from keras.layers import Dropout

In [13]:
#Adding the Layers(Input , Hidden and Output) to our ANN
classifier = Sequential()

classifier.add(Dense(20 , input_dim = 20 ,activation='relu'))
classifier.add(Dense(30 , activation='relu'))
classifier.add(Dense(30 , activation='relu'))
classifier.add(Dense(20 , activation='relu'))
classifier.add(Dense(10 , activation='relu'))
classifier.add(Dense(5 ,  activation='relu'))

classifier.add(Dense(1 , activation='sigmoid'))

classifier.compile(loss = 'binary_crossentropy' ,optimizer = 'adam' , metrics = ['accuracy'])

In [14]:
#Training our Ann
model_history = classifier.fit(X_train,Y_train,validation_split=0.30,batch_size=100,epochs=50)

Epoch 1/50
31/31 [==============================] - 1s 20ms/step - loss: 0.6211 - accuracy: 0.7876 - val_loss: 0.4901 - val_accuracy: 0.8138
Epoch 2/50
31/31 [==============================] - 0s 9ms/step - loss: 0.3869 - accuracy: 0.7982 - val_loss: 0.2678 - val_accuracy: 0.8153
Epoch 3/50
31/31 [==============================] - 0s 8ms/step - loss: 0.2405 - accuracy: 0.8593 - val_loss: 0.1756 - val_accuracy: 0.9502
Epoch 4/50
31/31 [==============================] - 0s 9ms/step - loss: 0.1519 - accuracy: 0.9556 - val_loss: 0.0996 - val_accuracy: 0.9602
Epoch 5/50
31/31 [==============================] - 0s 9ms/step - loss: 0.0875 - accuracy: 0.9629 - val_loss: 0.0658 - val_accuracy: 0.9762
Epoch 6/50
31/31 [==============================] - 0s 9ms/step - loss: 0.0620 - accuracy: 0.9734 - val_loss: 0.0515 - val_accuracy: 0.9770
Epoch 7/50
31/31 [==============================] - 0s 9ms/step - loss: 0.0511 - accuracy: 0.9760 - val_loss: 0.0446 - val_accuracy: 0.9785
Epoch 8/50
31/31 [=

In [15]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [16]:
# y_pred

In [17]:
# for i in range(len(y_pred)):
#     if y_pred[[i]] < 0.5:
#         y_pred[[i]] = 0
#     elif y_pred[i] > 0.5:
#         y_pred[[i]] = 1
#     elif y_pred[i] == 0.5:
#         y_pred[i] = 0.5

In [18]:
y_pred

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [False],
       [ True]])

In [19]:
Y_test

5145    1
502     1
2550    1
2260    1
3641    1
       ..
599     1
1590    1
1085    1
4184    0
649     1
Name: COVID-19, Length: 1087, dtype: int64

In [20]:
classifier.evaluate(X_test,Y_test)

34/34 [==============================] - 0s 4ms/step - loss: 0.0366 - accuracy: 0.9862


[0.03655749931931496, 0.9862005710601807]

In [21]:
# # Making the Confusion Matrix
# # Calculate the Accuracy
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report
cm = confusion_matrix(Y_test, y_pred)
score = accuracy_score(Y_test,y_pred)
clr = classification_report(Y_test,y_pred)
print(f"{score*100} %\n______________________\n{cm}\n______________________\n{clr}")

98.62005519779208 %
______________________
[[190   2]
 [ 13 882]]
______________________
              precision    recall  f1-score   support

           0       0.94      0.99      0.96       192
           1       1.00      0.99      0.99       895

    accuracy                           0.99      1087
   macro avg       0.97      0.99      0.98      1087
weighted avg       0.99      0.99      0.99      1087



In [22]:
X.head()

Breathing Problem  Fever  Dry Cough  Sore throat  Running 0se  Asthma  \
0                  1      1          1            1            1       0   
1                  1      1          1            1            0       1   
2                  1      1          1            1            1       1   
3                  1      1          1            0            0       1   
4                  1      1          1            1            1       0   

   Chronic Lung Disease  Headache  Heart Disease  Diabetes  Hyper Tension  \
0                     0         0              0         1              1   
1                     1         1              0         0              0   
2                     1         1              0         1              0   
3                     0         0              1         1              0   
4                     1         1              1         1              1   

   Fatigue   Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0         1                  1              0                           1   
1         1                  0              0                           0   
2         1                  1              1                           0   
3         0                  0              1                           0   
4         0                  1              0                           1   

   Attended Large Gathering  Visited Public Exposed Places  \
0                         0                              1   
1                         1                              1   
2                         0                              0   
3                         1                              1   
4                         0                              1   

   Family working in Public Exposed Places  Wearing Masks  \
0                                        1              0   
1                                        0              0   
2                                        0              0   
3                                        0              0   
4                                        0              0   

   Sanitization from Market  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0

In [23]:
classifier.predict([[1,0,0,1,1,1,0,1,0,1,1,1,0,1,1,1,0,1,0,0]])

array([[1.]], dtype=float32)

In [24]:
classifier.predict([[1,1,1,0,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0]])

array([[1.]], dtype=float32)

In [25]:
classifier.predict([[1,1,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0]])

array([[0.9999999]], dtype=float32)

In [26]:
classifier.predict([[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

array([[0.99671257]], dtype=float32)