In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv("Covid Dataset.csv")

In [3]:
dataset.head(5)

Breathing Problem  Fever  Dry Cough  Sore throat  Running nose  Asthma  \
0                  1      1          1            1             1       0   
1                  1      1          1            1             0       1   
2                  1      1          1            1             1       1   
3                  1      1          1            0             0       1   
4                  1      1          1            1             1       0   

   Chronic Lung Disease  Headache  Heart Disease  Diabetes  ...  Fatigue   \
0                     0         0              0         1  ...         1   
1                     1         1              0         0  ...         1   
2                     1         1              0         1  ...         1   
3                     0         0              1         1  ...         0   
4                     1         1              1         1  ...         0   

   Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0                  1              0                           1   
1                  0              0                           0   
2                  1              1                           0   
3                  0              1                           0   
4                  1              0                           1   

   Attended Large Gathering  Visited Public Exposed Places  \
0                         0                              1   
1                         1                              1   
2                         0                              0   
3                         1                              1   
4                         0                              1   

   Family working in Public Exposed Places  Wearing Masks  \
0                                        1              0   
1                                        0              0   
2                                        0              0   
3                                        0              0   
4                                        0              0   

   Sanitization from Market  COVID-19  
0                         0         1  
1                         0         1  
2                         0         1  
3                         0         1  
4                         0         1  

[5 rows x 21 columns]

In [4]:
X = dataset.iloc[:,0:20].values
Y = dataset.iloc[:,20].values

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.20 , random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

In [7]:
X_train

array([[-1.39826055,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       [ 0.71517429, -1.9076882 ,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       ...,
       [ 0.71517429,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [-1.39826055,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [ 0.71517429, -1.9076882 ,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ]])

In [8]:
X_test

array([[ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       [ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       [-1.39826055,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       ...,
       [ 0.71517429,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [-1.39826055, -1.9076882 , -1.93002591, ...,  1.19406082,
         0.        ,  0.        ],
       [ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ]])

In [9]:
X_train.shape

(4347, 20)

In [10]:
X_test.shape

(1087, 20)

In [11]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
Y_pred = classifier.predict(X_test)

In [13]:
Y_pred

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [14]:
Y_test

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [15]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
acc = accuracy_score(Y_test,Y_pred)*100
cm = confusion_matrix(Y_test, Y_pred)
cf = classification_report(Y_test,Y_pred)

In [16]:
print(f"ACCURACY :\n{acc}\n-----------------------------------------\nCONFUSION MATRIX:\n{cm}\n-----------------------------------------\nCLASSIFICATION REPORT :\n{cf}")

ACCURACY :
96.22815087396505
-----------------------------------------
CONFUSION MATRIX:
[[169  23]
 [ 18 877]]
-----------------------------------------
CLASSIFICATION REPORT :
              precision    recall  f1-score   support

           0       0.90      0.88      0.89       192
           1       0.97      0.98      0.98       895

    accuracy                           0.96      1087
   macro avg       0.94      0.93      0.93      1087
weighted avg       0.96      0.96      0.96      1087



In [27]:
print(f"______________________________\nACCURACY : {acc}\n______________________________")

______________________________
ACCURACY : 96.22815087396505
______________________________


In [33]:
print(f"______________________________\nCONFUSION MATRIX\n  \n {cm} \n______________________________")

______________________________
CONFUSION MATRIX
  
 [[169  23]
 [ 18 877]] 
______________________________


In [36]:
print(f"CLASSIFICATION REPORT : \n{cf}")

CLASSIFICATION REPORT : 
              precision    recall  f1-score   support

           0       0.90      0.88      0.89       192
           1       0.97      0.98      0.98       895

    accuracy                           0.96      1087
   macro avg       0.94      0.93      0.93      1087
weighted avg       0.96      0.96      0.96      1087

