In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv("Covid Dataset.csv")

In [3]:
dataset.head(5)

Breathing Problem  Fever  Dry Cough  Sore throat  Running nose  Asthma  \
0                  1      1          1            1             1       0   
1                  1      1          1            1             0       1   
2                  1      1          1            1             1       1   
3                  1      1          1            0             0       1   
4                  1      1          1            1             1       0   

   Chronic Lung Disease  Headache  Heart Disease  Diabetes  ...  Fatigue   \
0                     0         0              0         1  ...         1   
1                     1         1              0         0  ...         1   
2                     1         1              0         1  ...         1   
3                     0         0              1         1  ...         0   
4                     1         1              1         1  ...         0   

   Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0                  1              0                           1   
1                  0              0                           0   
2                  1              1                           0   
3                  0              1                           0   
4                  1              0                           1   

   Attended Large Gathering  Visited Public Exposed Places  \
0                         0                              1   
1                         1                              1   
2                         0                              0   
3                         1                              1   
4                         0                              1   

   Family working in Public Exposed Places  Wearing Masks  \
0                                        1              0   
1                                        0              0   
2                                        0              0   
3                                        0              0   
4                                        0              0   

   Sanitization from Market  COVID-19  
0                         0         1  
1                         0         1  
2                         0         1  
3                         0         1  
4                         0         1  

[5 rows x 21 columns]

In [4]:
X = dataset.iloc[:,0:20].values
Y = dataset.iloc[:,20].values

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.20 , random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

In [7]:
from sklearn.svm import SVC

classifier = SVC(probability=True)
classifier.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [8]:
y_pred = classifier.predict(X_test)

In [9]:
y_pred

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [10]:
Y_test

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [11]:
df = pd.DataFrame({'Actual':Y_test.flatten() , 'Predicted':y_pred.flatten()})

In [12]:
df.head(10)

Actual  Predicted
0       1          1
1       1          1
2       1          1
3       1          1
4       1          1
5       1          1
6       0          1
7       1          1
8       1          1
9       1          1

In [13]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(f"Accuracy : {accuracy_score(Y_test,y_pred) * 100}\n-----------------------------------------")
print(f"Confusion Matrix : \n{confusion_matrix(Y_test,y_pred)}\n-------------------------------------")
print(f"\nClassification Report : \n{classification_report(Y_test,y_pred)}")

Accuracy : 97.79208831646734
-----------------------------------------
Confusion Matrix : 
[[179  13]
 [ 11 884]]
-------------------------------------

Classification Report : 
              precision    recall  f1-score   support

           0       0.94      0.93      0.94       192
           1       0.99      0.99      0.99       895

    accuracy                           0.98      1087
   macro avg       0.96      0.96      0.96      1087
weighted avg       0.98      0.98      0.98      1087



In [14]:
classifier.predict([[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1]])

array([1], dtype=int64)

In [15]:
classifier.predict([[1,1,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1]])

array([1], dtype=int64)